### ISSUE TITLE
Feature: User can view the sudoku board

### ISSUE THREAD

**Issue by Stran1025** [Stran1025/sudokuller#1]
## ⚙️ Feature

> ##### User can view the sudoku board

## 📐 Functionality

> ##### When users clicked on new game it will direct them to a new sudoku board

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/97194085/171037582-b9430458-1faf-49c7-a9d2-b7c7cc5e6393.png)
![image](https://user-images.githubusercontent.com/97194085/171038154-a5f3fc91-e970-49a0-919e-111e00e1c2ec.png)
![image](https://user-images.githubusercontent.com/97194085/171042767-c89f3e66-e712-431e-aa87-63a48d56a768.png)
![image](https://user-images.githubusercontent.com/97194085/171042790-a79928c7-4056-44a5-aa40-a951ecfebf2b.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to create the the database schema and tables
- [x] Update `data.sql` to input the first initial challenges

### ☁️ Server

- [x] Create a general error function
- [x] Make a route for the get method
   - [x] path /api/sudoku
   - [x] send the user the challenge and the sudokuId
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component for the board
- [x] Display the challenge on to the board
### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
