### ISSUE TITLE
Feature: User can see incorrect inputs

### ISSUE THREAD

**Issue by Stran1025** [Stran1025/sudokuller#17]
## ⚙️ Feature

> ##### User can get feedback when they input an incorrect cell

## 📐 Functionality

> ##### When the user enter an obviously incorrect move such as repeating number in the same row, column or 3x3 cell blocks. The app will highlight the incorrect cells red.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![image](https://user-images.githubusercontent.com/97194085/172682512-84d97ee8-2381-4d2c-ab21-de518942ef27.png)
![image](https://user-images.githubusercontent.com/97194085/172682555-a5520a69-573e-4ac7-b07c-57a929354311.png)
![image](https://user-images.githubusercontent.com/97194085/172682576-73fb038f-0afe-413d-9d37-e86cb0a16db4.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] when the user input in a cell check
  - [x]  if that row already have that number
    - [x] Array.includes
  - [x] if the column already have that number
    - [x] Check the index
  - [x] or if the 3x3 cells block contain that number
    - [x] check the index range 1-3, 4-6, 7-9
    - [x] and the column range
  - [x] Hightlight all duplicate number red
  - [x] When user undo or erase the incorrect mark remove the red highlight

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
