### ISSUE TITLE
Feature: User can pause the timer

### ISSUE THREAD

**Issue by Stran1025** [Stran1025/sudokuller#19]
## ⚙️ Feature

> ##### Users can pause the timer 

## 📐 Functionality

> ##### When User hit the icon next to the timer
the timer is paused and the board is cover up

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![image](https://user-images.githubusercontent.com/97194085/172724473-56a9e3bc-1344-4263-b188-bc0a67f7b738.png)
![image](https://user-images.githubusercontent.com/97194085/172724494-1add7779-28d3-47e3-877a-3ac00bbb33a7.png)
![image](https://user-images.githubusercontent.com/97194085/172724503-df0be591-0847-4817-b635-3df54ecb684e.png)
![image](https://user-images.githubusercontent.com/97194085/172724513-da3f12d5-9166-460a-ae6d-9aecfc5d5393.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
### ⚡ Client

- [ ] Start the timer when the board is loaded
  - [ ] when user hit the icon
    - [ ] paused the timer
    - [ ] cover up the board with a modal
 - [ ] when the user click the modal or the icon again
 - [ ] resume the timer and uncover the board

### 🧑‍⚕️ Clean Up

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
