### ISSUE TITLE
Feature: User can input numbers into the boards

### ISSUE THREAD

**Issue by Stran1025** [Stran1025/sudokuller#2]
## ⚙️ Feature

> ##### User can input numbers into the boards

## 📐 Functionality

> ##### When the user input a number check if the input is valid. If it is then send a post request to the server with the number

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![image](https://user-images.githubusercontent.com/97194085/171282682-6fc517e5-a362-4465-88ad-452b40cec67f.png)
![image](https://user-images.githubusercontent.com/97194085/171282695-f9fdb2a1-7e29-4727-b2a0-1dbde1cb1616.png)
![image](https://user-images.githubusercontent.com/97194085/171282707-41c87938-a1f4-49e8-aef2-a7415a9cfbde.png)
![image](https://user-images.githubusercontent.com/97194085/171282744-7d98e379-ecc6-46ac-9cf1-4d25ef8a8416.png)
![image](https://user-images.githubusercontent.com/97194085/171282758-f3d0eb55-4e19-4880-87ed-c3d8f64423d9.png)
![image](https://user-images.githubusercontent.com/97194085/171282770-d3631a8a-2650-4361-bc40-8fb8f5d09cbd.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `data.sql` to add 10 more challenges

### ☁️ Server

- [x] Update `server/index.js` to accept POST request
   - [x] to api/solution
   - [x] Send back the solutionId
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to for the number pad
- [x] Display the number pad on the screen
- [x] Add an event listener to the number pad
  - [x] Delegate the event to each number
  - [x] Every time the change the number at the spot into the clicked number
     - [x] if the input is invalid turn the cells background light red 
### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
