### ISSUE TITLE
Feature: User can submit their solution

### ISSUE THREAD

**Issue by Stran1025** [Stran1025/sudokuller#21]
## ⚙️ Feature

> ##### User can submit their solution

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![image](https://user-images.githubusercontent.com/97194085/172903833-7a8497fd-daa0-4fc9-b532-d1f85a4372ee.png)
![image](https://user-images.githubusercontent.com/97194085/172903847-76d20cfa-3498-47e2-95dd-9ec90bd992e1.png)
![image](https://user-images.githubusercontent.com/97194085/172903859-c3260a14-fe48-4a61-bfc6-a934c2b70378.png)
![image](https://user-images.githubusercontent.com/97194085/172903869-4d168010-a5da-4a05-95cd-41a4b79a276c.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to accept a post route with api/solution
  - [x] Check if the user send a token
    - [x] If there is a token
    - [x] decode the token and verify it 
- [x] Insert the solution to the database 
- [x] if there is no token send back a response with the time
- [x] Response with the solutionId and the time
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] add a submit button to the board page
- [x] When the user hit submit button
  - [x] Check if the all cells is filled
  - [x] Check if all cells match the solution
- [x] If any of the check is fail pop up a message with the reason
- [x] If all checks is passed send a fetch request to the server
- [x] Pop up a modal 
  - [x] Display the time from the server response body
  - [x] Provide the user a home button
    - [x] when click change the hash route to home

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
