### ISSUE TITLE
Feature: User can undo previous input

### ISSUE THREAD

**Issue by Stran1025** [Stran1025/sudokuller#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes
![image](https://user-images.githubusercontent.com/97194085/171043787-3b642737-ef80-4f00-ba31-5702caafb03c.png)
![image](https://user-images.githubusercontent.com/97194085/171043794-c183afd8-70f9-4245-8560-224a0d02e78b.png)
![image](https://user-images.githubusercontent.com/97194085/171043800-c4c61a33-28e9-421f-ac4d-f1ef88e201e9.png)
![image](https://user-images.githubusercontent.com/97194085/171043806-2f148d5b-104e-43dd-9a60-1d159e7cdc9a.png)
![image](https://user-images.githubusercontent.com/97194085/171043814-79a57dc0-87a8-451a-accc-e81c1b666e3b.png)
![image](https://user-images.githubusercontent.com/97194085/171043828-46e3ae21-7a79-45a7-ba23-bf750ae9b36c.png)
![image](https://user-images.githubusercontent.com/97194085/171043839-20a1059b-6222-410d-a789-d5c0bf48a83a.png)
![image](https://user-images.githubusercontent.com/97194085/171043846-6f5a53fc-1255-4333-bb76-bdf9a3956870.png)
![image](https://user-images.githubusercontent.com/97194085/171043854-d9c31b68-e3ee-44b5-ae76-be693f66aa87.png)
![image](https://user-images.githubusercontent.com/97194085/171043861-38b77c20-6506-4de5-b993-a853c83a4607.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `data.sql` to add 10 more challenges

### ⚡ Client

- [x] Create a component for the undo button
- [x] Have a state to keep track of previous move location
- [x] For each move make a copy of the previous state of the challenge
   - [x] Push the challenge into the undo state array
- [x] When the undo button is clicked
  - [x] Use the last item into undo state array to render a new state with the previous input

### 🧑‍⚕️ Clean Up
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
