### ISSUE TITLE
Feature: User can put pencil marks on cells

### ISSUE THREAD

**Issue by Stran1025** [Stran1025/sudokuller#4]
## ⚙️ Feature

> ##### Users can put pencil marks into cells to mark for numbers that cell could contain.

## 🖼️ Wireframes
![image](https://user-images.githubusercontent.com/97194085/171043934-f9e9a84b-5d2e-4a21-946b-5e4f64613f0e.png)
![image](https://user-images.githubusercontent.com/97194085/171043942-10828179-872e-43d7-bb88-fc64f01219ed.png)
![image](https://user-images.githubusercontent.com/97194085/171043948-4d467d35-182b-4c2f-a876-f51fe2a0126e.png)
![image](https://user-images.githubusercontent.com/97194085/171044005-fb84b12f-8757-4183-adc3-e63a559c82d6.png)
![image](https://user-images.githubusercontent.com/97194085/171044010-e850bf8d-7bcc-4258-a590-6519546f72ef.png)
![image](https://user-images.githubusercontent.com/97194085/171044016-13f405df-a48e-4289-8efe-4ff79416ad58.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Create a component to for the pencil icon
- [x] Pencil Icon is togglable
   - [x] Change state when the icon is clicked
   - [x] When it is toggle on
      - [x] All input is pencil mark
- [x] Store the pencil mark in an arrays with the coordinates
- [x] Adjusted the board to check if there are pencil marks
   - [x] Put the correct pencil marks in the correct coordinates
   - [x] Smaller fonts for the pencil marks
- [x] Make sure that the pencil marks appear in the right place (ie 4 under the 1 and the 7 under the 4 like a numpad)

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
