### ISSUE TITLE
Feature: User can erase an input cells

### ISSUE THREAD

**Issue by Stran1025** [Stran1025/sudokuller#5]
## ⚙️ Feature

> ##### Users can delete any cell on the board
Both numbers and pencil marks will get erase

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/97194085/171044090-78fafd3c-ed38-47d4-acd4-ba5c2fcf5b18.png)
![image](https://user-images.githubusercontent.com/97194085/171044104-6eaf0e3f-e45f-4a04-84e0-3535d212459b.png)
![image](https://user-images.githubusercontent.com/97194085/171044119-e079dc4b-9696-4543-ad5e-71b793d795b9.png)
![image](https://user-images.githubusercontent.com/97194085/171044124-bf1e86f3-ba0b-4414-a516-a5f10da24cbb.png)
![image](https://user-images.githubusercontent.com/97194085/171044128-cb80e112-143f-475d-9e1d-97a80c77b480.png)
![image](https://user-images.githubusercontent.com/97194085/171044141-77204e04-e04f-4806-a1ad-87f4e0095677.png)
![image](https://user-images.githubusercontent.com/97194085/171044146-0f258d30-5679-4160-b0b6-688ea791e2b9.png)
![image](https://user-images.githubusercontent.com/97194085/171044154-becbed6e-2eab-4ee4-8267-38a2192667c3.png)
![image](https://user-images.githubusercontent.com/97194085/171044157-8b1eed27-14f2-466f-8827-6dd7f0b38192.png)
![image](https://user-images.githubusercontent.com/97194085/171044166-f7606735-ed62-4bbc-9839-70e730847a84.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Create an erase icon
- [x] When user clicked on the erase icon 
  - [x] The the highlighted/selected cell value get set back to 0
  - [x] If there are no selected cell then return
- [x] If the user clicked on delete while pencil mark is toggle true make sure is remain true after erasing a cell
- [x] Everything remain the same if user try to erase an empty cell
### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
