### ISSUE TITLE
Feature: User can play sudoku

### ISSUE THREAD

**Issue by Stran1025** [Stran1025/sudokuller#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes
![image](https://user-images.githubusercontent.com/97194085/171044272-72569b23-5c6c-4a9d-9e5b-d2fa7fb8872a.png)
![image](https://user-images.githubusercontent.com/97194085/171044280-70a846c9-e200-4e89-ae58-3544c2222684.png)
![image](https://user-images.githubusercontent.com/97194085/171044295-3a530a12-b4a7-45f1-9278-b6202106417b.png)
![image](https://user-images.githubusercontent.com/97194085/171044301-e75a1135-db10-40a2-8142-373f50704edf.png)
![image](https://user-images.githubusercontent.com/97194085/171044307-13c024bf-66ee-4d70-a5a4-38be76e27bf2.png)
![image](https://user-images.githubusercontent.com/97194085/171044312-d41af3b3-d4c1-419d-bd85-a8626ecc2bc4.png)
![image](https://user-images.githubusercontent.com/97194085/171044314-21c96b58-91bf-48dd-a183-96d6ae10bb27.png)
![image](https://user-images.githubusercontent.com/97194085/171044320-424b183d-e814-4561-9c3a-914200698858.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [ ] make a server route that accept POST requests
- [ ] Accepting JSON object
   - [ ] the object must include the sudokuId
   - [ ] who solved the puzzle (userId) or (token)
   - [ ] How long did it take for them to solve (time)
   - [ ] 

### ⚡ Client

- [ ] Create a component to ...
- [ ] Update component to ...

### 🧑‍⚕️ Clean Up

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
