### ISSUE TITLE
Feature: User can can make their own profiles

### ISSUE THREAD

**Issue by Stran1025** [Stran1025/sudokuller#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can sign up for an account and make their own profiles

## 🖼️ Wireframes
![image](https://user-images.githubusercontent.com/97194085/171044441-7ed7795e-814a-4186-bfae-783726d6a64e.png)
![image](https://user-images.githubusercontent.com/97194085/171044446-b7dfb73b-8d76-41df-8038-e73ccf1f5b97.png)
![image](https://user-images.githubusercontent.com/97194085/171044453-7e48b65c-1413-4239-8924-c9a9b6fa535f.png)
![image](https://user-images.githubusercontent.com/97194085/171044456-d277321d-b996-4cf2-9a8b-feb876d600b2.png)
![image](https://user-images.githubusercontent.com/97194085/171044465-f5f0f45d-a891-4c7b-8fa2-dfc66c5a6efb.png)
![image](https://user-images.githubusercontent.com/97194085/171044475-91f57f94-b4dd-4e74-9e13-03979688a6d4.png)
![image](https://user-images.githubusercontent.com/97194085/171044483-4de4df66-3af1-4a6f-a06d-517223abe396.png)
![image](https://user-images.githubusercontent.com/97194085/171044488-1ed978b9-71a7-4a18-be06-49a535ac5bcb.png)
![image](https://user-images.githubusercontent.com/97194085/171044493-f6d76749-0d8d-417c-b7d1-187f21119844.png)
![image](https://user-images.githubusercontent.com/97194085/171044500-850d5d27-ff49-4ecb-9f4c-490b6a223d16.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `data.sql` to insert some demo and dummy users into the `users` table

### ☁️ Server

- [x] Update `server/index.js` to accept a post request 
  - [x] Path is /api/sign-up
  - [x] The req body must contain a unique username
    - [x] A password
  - [x] If the username is not unique send back an error with detail
  - [x] if the username or password is missing send back an error with detail
  - [x] send back the an object with username ,userId, time created,  and a token
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to for the sign-up page
- [x] Setup a hash route for sign-up page
- [x] Setup a hash route for the board page
- [x] Add a component did mount for when the user access the home page
  - [x] Pull the token from local storage
- [x] the user submit the sign-up forms if the username or password is required
- [x] If the server send back that the username is already taken 
  - [x] pop up a modal and tell the user that their username is taken
- [x]  If the server send back a response with a user obj
  - [x] save the token to local storage
  
### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
