### ISSUE TITLE
Feature: User can view their profiles

### ISSUE THREAD

**Issue by Stran1025** [Stran1025/sudokuller#8]
## ⚙️ Feature

> Users can view their profiles

## 🖼️ Wireframes
![image](https://user-images.githubusercontent.com/97194085/171044577-86a68041-cbd6-40e2-9adc-5d38e9b98737.png)
![image](https://user-images.githubusercontent.com/97194085/171044589-392e3aa0-aa5b-48d0-b2cd-9207e76cd18a.png)
![image](https://user-images.githubusercontent.com/97194085/171044596-30061b74-e8c0-43af-9699-8a4905e4a6ea.png)
![image](https://user-images.githubusercontent.com/97194085/171044602-8d8eb696-859e-4857-ab87-25f244c0663a.png)
![image](https://user-images.githubusercontent.com/97194085/171044609-7e086419-e904-460d-b023-3e5de35da6ed.png)
![image](https://user-images.githubusercontent.com/97194085/171044614-5f9c3c0c-00ea-4c2d-b6af-0bc4a68fd35a.png)
![image](https://user-images.githubusercontent.com/97194085/171044700-364a48c2-266c-441d-9173-3736b1a1a9ee.png)
![image](https://user-images.githubusercontent.com/97194085/171044708-f3bb0f68-dbc1-4f89-9f51-58cb59ef2a41.png)
![image](https://user-images.githubusercontent.com/97194085/171044712-eb9e2996-b83e-4230-b804-85ed2da43352.png)
![image](https://user-images.githubusercontent.com/97194085/171044718-6d80c8a1-40ca-4d4d-90c0-4393163b00ea.png)
![image](https://user-images.githubusercontent.com/97194085/171044727-4a93ce41-9314-45dd-a5c1-2b0dc282c1bc.png)
![image](https://user-images.githubusercontent.com/97194085/171044732-bd2c8d27-931b-4ea9-a112-b13632358c62.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to accept a get request with 
  - [x] path api/auth/sign-in
  - [x] response with the data for the user profile such as their firstname
  - [x] total number of challenges completed
  - [x] total number of challenged created
  - [x] and current amount of experience
  - [x] and a token
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] make a profile page
- [x] have the user login
- [x] display the card for the user profile
### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
